//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALAM
    {
        public CALAM()
        {
            this.LICHLAMVIECs = new HashSet<LICHLAMVIEC>();
        }
    
        public string MACA { get; set; }
        public string THOIGIAN { get; set; }
        public Nullable<int> SOTIENG { get; set; }
    
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs { get; set; }
    }
}
