//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BANGLUONG
    {
        public string MABANGLUONG { get; set; }
        public string MANV { get; set; }
        public string MATHUQUY { get; set; }
        public Nullable<int> TONGTIME { get; set; }
        public Nullable<int> HESOLUONG { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual BANGLUONG BANGLUONG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
