
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataEntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class HOADON
{

    public HOADON()
    {

        this.VEs = new HashSet<VE>();

    }


    public string MAHD { get; set; }

    public string MANV { get; set; }

    public string MAKH { get; set; }

    public Nullable<System.DateTime> NGAYBAN { get; set; }

    public Nullable<int> GIAVE { get; set; }

    public Nullable<int> SOLUONG { get; set; }

    public Nullable<int> GIATIEN { get; set; }



    public virtual KHACHHANG KHACHHANG { get; set; }

    public virtual NHANVIEN NHANVIEN { get; set; }

    public virtual ICollection<VE> VEs { get; set; }

}

}
