
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataEntityFramework
{

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
public partial class NHANVIEN
{

    public NHANVIEN()
    {

        this.CT_BANGLUONG = new HashSet<CT_BANGLUONG>();

        this.HOADONs = new HashSet<HOADON>();

        this.LICHLAMVIECs = new HashSet<LICHLAMVIEC>();

        this.LICHLAMVIECs1 = new HashSet<LICHLAMVIEC>();

    }

    [Display(Name="Mã nhân viên")]
    public string MANV { get; set; }

    public string PASSWORD { get; set; }
    [Display(Name = "Họ tên")]
    public string HOTEN { get; set; }
       [Display(Name = "Ngày sinh")]
    public Nullable<System.DateTime> NGAYSINH { get; set; }
       [Display(Name = "Giới tính")]
    public string GIOITINH { get; set; }

    public string MACHUCVU { get; set; }
       [Display(Name = "Ngày vào làm")]
    public Nullable<System.DateTime> NGAYVAOLAM { get; set; }

    public string CMND { get; set; }
    [EmailAddress(ErrorMessage = "Email sai cú pháp !")]
    public string EMAIL { get; set; }
       [Display(Name = "Di động")]
    public string SDT { get; set; }
       [Display(Name = "Địa chỉ")]
    public string DIACHI { get; set; }
       [Display(Name = "Tình trạng")]
    public string TINHTRANG { get; set; }

    public byte[] AVARTA { get; set; }



    public virtual CHUCVU CHUCVU { get; set; }

    public virtual ICollection<CT_BANGLUONG> CT_BANGLUONG { get; set; }

    public virtual ICollection<HOADON> HOADONs { get; set; }

    public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs { get; set; }

    public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs1 { get; set; }

}

}
