//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGCHIEU
    {
        public PHONGCHIEU()
        {
            this.LICHCHIEUx = new HashSet<LICHCHIEU>();
        }
    
        public string MAPHONGCHIEU { get; set; }
        public string TENPHONGCHIEU { get; set; }
        public Nullable<int> SOGHE { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual ICollection<LICHCHIEU> LICHCHIEUx { get; set; }
    }
}
