//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGLUONG
    {
        public BANGLUONG()
        {
            this.CT_BANGLUONG = new HashSet<CT_BANGLUONG>();
        }
    
        public string MABANGLUONG { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<decimal> TONG { get; set; }
    
        public virtual ICollection<CT_BANGLUONG> CT_BANGLUONG { get; set; }
    }
}
