//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHIEU
    {
        public LICHCHIEU()
        {
            this.VEs = new HashSet<VE>();
        }
    
        public string MALICHCHIEU { get; set; }
        public string MAPHIM { get; set; }
        public string PHIENBAN { get; set; }
        public string MAPHONGCHIEU { get; set; }
        public Nullable<System.DateTime> NGAYCHIEU { get; set; }
        public string GIOBATDAU { get; set; }
        public string GIOKETTHUC { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual CT_PHIM CT_PHIM { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        public virtual ICollection<VE> VEs { get; set; }
    }
}
