//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.CT_BANGLUONG = new HashSet<CT_BANGLUONG>();
            this.HOADONs = new HashSet<HOADON>();
            this.LICHLAMVIECs = new HashSet<LICHLAMVIEC>();
            this.LICHLAMVIECs1 = new HashSet<LICHLAMVIEC>();
        }
    
        public string MANV { get; set; }
        public string PASSWORD { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string MACHUCVU { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
        public string CMND { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public string TINHTRANG { get; set; }
        public byte[] AVARTA { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual ICollection<CT_BANGLUONG> CT_BANGLUONG { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs { get; set; }
        public virtual ICollection<LICHLAMVIEC> LICHLAMVIECs1 { get; set; }
    }
}
