//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public PHIM()
        {
            this.CT_PHIM = new HashSet<CT_PHIM>();
        }
    
        public string MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public string CONGNGHE { get; set; }
        public string THELOAI { get; set; }
        public string QUOCGIA { get; set; }
        public Nullable<int> THOILUONG { get; set; }
        public string DAODIEN { get; set; }
        public string DIENVIEN { get; set; }
        public string TINHTRANG { get; set; }
        public string CHITIET { get; set; }
    
        public virtual ICollection<CT_PHIM> CT_PHIM { get; set; }
    }
}
