//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapChieuPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        public VE()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MAVE { get; set; }
        public string MALICHCHIEU { get; set; }
        public Nullable<int> STTGHE { get; set; }
    
        public virtual LICHCHIEU LICHCHIEU { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
